
<h1>Categorias</h1>

<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Nome</th>
			<th>Ação</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->data as $entity): ?>
			<tr>
				<td><?= $entity->getId(); ?></td>
				<td><?= $entity->getNome(); ?></td>
				<td></td>
			</tr>
		<?php endforeach; ?>		
	</tbody>
	<tfoot>
		
	</tfoot>
</table>
<br />

<?php  echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>	


