
<h1>Categorias</h1>

<a class="btn btn-primary" href="<?php echo $this->url('livraria-admin-interna', ['controller' => 'categorias', 'action' => 'new']); ?>">Criar nova categoria</a>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>Id</th>
			<th>Nome</th>
			<th>Ação</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->data as $entity): ?>
			<tr>
				<td><?= $entity->getId(); ?></td>
				<td><?= $entity->getNome(); ?></td>
				<td>
				  <a class="btn btn-info" href="<?php echo $this->url('livraria-admin-interna', ['controller' =>'categorias', 'action' => 'edit', 'id' => $entity->getId()]); ?>">Alterar</a>
				  <a class="btn btn-danger" href="<?php echo $this->url('livraria-admin-interna', ['controller' =>'categorias', 'action' => 'remover', 'id' => $entity->getId()]); ?>">Remover</a>
				</td>
			</tr>
		<?php endforeach; ?>		
	</tbody>
	<tfoot>
		
	</tfoot>
</table>
<br />

<?php  echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>	


