<h1>Nova categoria</h1>

<?php  
	$form = $this->form;

	$form->setAttribute('action', $this->url('livraria-admin',['controller' => 'categorias', 'action' => 'new']));

	$form->prepare();

	echo $this->form()->openTag($form);

	echo $this->formHidden($form->get('id'));

	echo $this->formRow($form->get('nome'));

	echo $this->formSubmit($this->form->get('submit'));

	echo $this->form()->closeTag();
?>